/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  studente
 * Created: 11-mag-2016
 */
CREATE TABLE Users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    fname VARCHAR(128) NOT NULL,
    lname VARCHAR(128) NOT NULL,
    usertype BOOLEAN NOT NULL
);

CREATE TABLE Items
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemName VARCHAR(128) NOT NULL,
    description VARCHAR(1024),
    quantity INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    category VARCHAR(32),
    img VARCHAR (1024),
    vendId INTEGER NOT NULL,
    FOREIGN KEY (vendId) REFERENCES Users(id)
);

CREATE TABLE Accounts
(
    userId INTEGER PRIMARY KEY NOT NULL,
    balance DOUBLE NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id)
);


INSERT INTO users (id, username, password, fname, lname, usertype)
VALUES (default, 'elon.musk', 'em', 'Elon', 'Musk', false),
(default, 'bill.gates', 'bg', 'Bill', 'Gates', false),
(default, 'gino.paoli', 'gp', 'Gino', 'Paoli', true),
(default, 'paolo.brosio', 'pb', 'Paolo', 'Brosio', true);

INSERT INTO Items (id, itemName, description, quantity, price, category, img, vendId)
VALUES (default, 'D510 MT Desktop Computer', 'Generic Desktop description', 10, 799.99, 'desktop', 'M2/img/Desktop1.jpg', 3),
(default, 'Apple Iphone 6', 'Generic Iphone description', 1, 699.99, 'smartphone', 'M2/img/Iphone1.jpg', 3),
(default, 'Samsung Galaxy s6', 'Generic Samsung description', 5, 599.99, 'smartphone', 'M2/img/GalaxyS6.jpg', 3),
(default, 'Western Digital Caviar Black 1 TB', 'Generic HDD description', 15, 79.99, 'accessories', 'M2/img/HDD1.jpg', 3),
(default, 'ASUS - Notebook con Monitor 15,6 Full HD', 'Generic Laptop description', 125, 2999.99, 'laptop', 'M2/img/Laptop1.jpg', 4),
(default, 'ASUS - VS228DE Monitor 21.5', 'Generic Monitor description', 15, 179.99, 'accessories', 'M2/img/Monitor1.jpg', 4),
(default, 'Hannspree Tablet PC 10,1', 'Generic Tablet description', 15, 479.99, 'tablet', 'M2/img/HannspreeTablet1.jpg', 4);

INSERT INTO Accounts (userId, balance)
VALUES (1, 3000.00),
(2, 1000.50),
(3, 1234.12),
(4, 0.00);

