/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  studente
 * Created: 11-mag-2016
 */
CREATE TABLE Users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    fname VARCHAR(128) NOT NULL,
    lname VARCHAR(128) NOT NULL
);

CREATE TABLE Items
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemName VARCHAR(128) NOT NULL,
    description VARCHAR(1024),
    quantity INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    category VARCHAR(32)
);

CREATE TABLE Accounts
(
    userId INTEGER PRIMARY KEY NOT NULL,
    balance DOUBLE NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Sales
(
    vendId INTEGER NOT NULL,
    itemID INTEGER NOT NULL,
    PRIMARY KEY (vendId, itemId),
    FOREIGN KEY (vendId) REFERENCES Users(id),
    FOREIGN KEY (itemId) REFERENCES Items(id)
);